# Generated by Django 5.0.6 on 2024-06-18 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAdmin', '0003_alter_addproduct_category_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='Description',
            field=models.TextField(default=''),
        ),
    ]
