# Generated by Django 5.0.6 on 2024-06-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAdmin', '0004_alter_addproduct_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproduct',
            name='Product_price',
            field=models.IntegerField(null=True),
        ),
    ]
